# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.
import random
number = str(random.randint(1000, 9999))  #random 4 digit number
print number
counter = 0
guess = 1
answer = 0
number_list = []
number_list.append(number)
guess_list = []
guess_list.append(guess)
answer_list = []
bull = 0
cow = 0
print "Welcome to the cows and bulls game!"
while guess != 0000 and cow != 4:
    guess = int(raw_input("Guess a 4-digit number or type 0000 to exit."))
    for number in number_list:
        number_list.append(number)
    for number in guess_list:
        guess_list.append(number)
    if guess == number:
            answer = guess
            print "You got the answer!"
    if number_list[counter] == guess_list[counter]:
        answer_list[counter] = number_list[counter]
        cow = cow + 1
        print "You have" + " cows and" + " bulls."
    counter = counter + 1

